[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With,Content-Type,Accept,Origin"

# Configuração para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fallback para página estática em caso de erro
[[redirects]]
  from = "/*"
  to = "/fallback.html"
  status = 404

# Configuração específica para a função de teste PIX
[[redirects]]
  from = "/api/test-pix"
  to = "/.netlify/functions/pagarme/test-pix"
  status = 200
  force = true

# Configuração para o webhook do Pagar.me
[[redirects]]
  from = "/webhook/pagarme"
  to = "/.netlify/functions/pagarme/webhook"
  status = 200
  force = true

# Definição de funções serverless
[functions]
  directory = "api"
  node_bundler = "esbuild" 